import React from 'react';
import { Brand_AI, Quizgenerator } from '../../components';
import './FizzBuzz.css';

function FizzBuzz() {
  return (
    <div className="Appp">
      <header className="App-header">
        <h1>Welcome to the next generation of stupid ass quizzes!</h1>
      </header>
      <main>
        <h2>What is your personality according to your choices ? Generated by Davinci003</h2>
        <p>Start the quiz to find out!</p>
      <Quizgenerator></Quizgenerator>

      </main>
      <Brand_AI></Brand_AI>
    </div>
  );
}

export default FizzBuzz;